[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.21"

[rpc_endpoints]
filecoin_calibration = "https://api.calibration.node.glif.io/rpc/v1"

[etherscan]
filecoin_calibration = { key = "${FILECOIN_EXPLORER_API_KEY}", url = "https://calibration.filscan.io/api" }
